# Generated by Django 4.2.4 on 2023-09-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ФИО')),
                ('profession', models.CharField(max_length=20, verbose_name='Профессия')),
                ('about_me', models.TextField(verbose_name='О себе')),
                ('hobby', models.TextField(verbose_name='Хобби')),
            ],
            options={
                'verbose_name': 'О себе',
                'verbose_name_plural': 'О себе',
            },
        ),
    ]
